#!/bin/sh
case $1 in -x) set -x; shift; esac
set -eu


# based on man page about abduco version: 0.6-6

case ${1-} in --help)
	printf %s\\n \
		"Usage: abduco [-e detachkey] [-r] [-f] -c name command [args ...]" \
		"       abduco [-e detachkey] [-r] [-f] -n name command [args ...]" \
		"       abduco [-e detachkey] [-r] [-f] [-l] -A name command [args ...]" \
		"       abduco [-e detachkey] [-r] [-l] -a name" \
		"" \
		"If no command line arguments are given all" \
		"currently active sessions are printed" \
		"sorted by their respective creation date." \
		"Lines starting with an asterik" \
		"* indicate that at least one client is connected." \
		"A plus sign + indicates that the command terminated" \
		"while no client was connected, attach to get its exit status." \
		"" \
		"-v|--version    Print version information to standard output and exit." \
		"" \
		"-r|--readonly   Readonly session, i.e. user input is ignored." \
		"" \
		"-e|--detachkey detachkey" \
		"                Set the key to detach which by default is set to CTRL+\\ i.e. ^\\ to detachkey." \
		"" \
		"-f|--force      Force creation of session when there is an already terminated session of the same name, after showing its exit status." \
		"" \
		"-c|--create     Create a new session and attach immediately to it." \
		"" \
		"-n|--new        Create a new session but do not attach to it." \
		"" \
		"-A|--attach-create" \
		"                Try to connect to an existing session, upon failure create said session and attach immediately to it." \
		"" \
		"-a|--attach     Attach to an existing session." \
		"" \
		"-l|--lowest-priority" \
		"                Attach with the lowest priority, meaning this client will be the last to control the size. " \
	;
	exit
esac

toshift=$#
#unset first
for i; do
	##case ${first+x} in '')
	##	set --
	##	first=x
	##esac

	case $i in
		--version)         set -- "$@" -v;;
		--readonly)        set -- "$@" -r;;
		--detachkey)       set -- "$@" -e;;
		--force)           set -- "$@" -f;;
		--create)          set -- "$@" -c;;
		--new)             set -- "$@" -n;;
		--attach-create)   set -- "$@" -A;;
		--attach)          set -- "$@" -a;;
		--lowest-priority) set -- "$@" -l;;
		*)                 set -- "$@" "$i";;
	esac

done
shift $toshift


## TODO: use var  ABDUCO_NAME if not specifyed `name`, also export to env from options to ABDUCO_NAME var
## but bash/sh is really bad languase for this job..
## how to check when opts end and program args begin, without shifting or modifying all args "$@"
#
## (
## # ABDUCO_NAME
## # ABDUCO_SESSION_NAME
## while :; do
## 	set -- "$@" "$i"
## done
## )

(
	case ${1-} in
			--help) ;; # --version
			-v) ;; # --version

			-e) false;; # --detachkey

			-r) false;; # --readonly
			#-f) ;; # --force
			-c) false;; # --create
			-n) false;; # --new
			-A) false;; # --attach
			-a) false;; # --attach
			-l) case $# in 1) true;; *) false;; esac;; # --list or --lowest
	esac || {
		sleep 1
		printf '\033[?1049l'
	}
)&

exec /usr/bin/abduco "$@"
