#!/bin/bash

# SOURCE: /bin/neofetch

# get_local_ip() {
    # case $os in
        # "Linux" | "BSD" | "Solaris" | "AIX" | "IRIX")
            local_ip="$(ip route get 1 | awk -F'src' '{print $2; exit}')"
            local_ip="${local_ip/uid*}"
            [[ -z "$local_ip" ]] && local_ip="$(ifconfig -a | awk '/broadcast/ {print $2; exit}')"
        # ;;
    # esac
# }



set -- "$local_ip"
# trim() {
    # set -f
    # shellcheck disable=2048,2086
    # set -- $*
    printf '%s\n' "${*//[[:space:]]/}"
    # set +f
# }

