#!/bin/sh
set -eu

i=$(abduco -l | grep -v '^Active session' | fzf +s --tac)
if command -v $ >/dev/null; then
	exec $ exec abduco -A "${i##*["$IFS"]}"  # run with '$' in order to get aliased version
else
	exec abduco -A "${i##*["$IFS"]}"
fi
