#!/bin/sh

case $1 in --help)
printf %s\\n \
	"Usage: ${0##*/} [--args=ARGS TO PASS TO MV] [FILE TO RENAME]..." \
;
exit
esac


die() {
	printf %s\\n >&2 "$1"
	exit ${2-2}
}


case $1 in --args=*)
	args=${1#*=}; shift
	eval "mv() { command mv $args \"\$@\"; }"
esac

case $1 in
	--) shift;;
	-*) die "see --help for usage";;
esac




t=$(mktemp)
trap 'rm -f -- "$t"' EXIT QUIT KILL

printf %s\\n "$@" > "$t" || exit

"${EDITOR:-vi}" "$t" || exit

t_count=$(wc -l < "$t")

case $t_count in $#) ;; *)
	die "lines missmatch there is $# files to mv, but edited file has $t_count lines"
esac


failed=0
for old; do
	IFS= read -r new || die "cant get new name for '$old' file, got: '$new'" $?

	case $old in "$new") printf %s\\n >&2 "nothing to change for file: '$old'"; continue; esac

	mv <&3 -- "$old" "$new" || {
		printf %s\\n "failed($?): mv $args${args+ }-- '$old' '$new'"
		failed=$(( failed + 1 ))
	}
done <"$t" 3<&0

case $failed in 0) ;; *)
	printf %s\\n >&2 "failed: $failed/$#"
	exit 1
esac
