#!/bin/sh-c fzf<
## Portuguese
🤣 Smileys & Emotion
🤷 People & Body
🐼 Animals & Nature
🍕 Food & Drink
💯 Symbols
🌇 Travel & Places
📮 Objects
🎈 Activities
🇺🇸 Flags
🌈 Thematic emojis
🎉 Holidays
🎲 Random emoji
🤣 Smileys & Emotion
🤷 People & Body
🐼 Animals & Nature
🍕 Food & Drink
💯 Symbols
🌇 Travel & Places
📮 Objects
🎈 Activities
🇺🇸 Flags
🌈 Thematic emojis
🎉 Holidays
🎲 Random emoji
🤖 A complete collection of Google emojis for Chrome OS, Pixel and Android

#Google Emoji is a set of emojis that have a unique design and are fundamentally different, for example, from  Apple and Microsoft emojis. They are used in Google software, in Chrome OS, in their email client, on Pixel devices and on most Android devices.
#
#Below is the current list of emojis taking into account the latest Android 10.0 system update.
#
#“You never lose a dream, it just incubates as a hobby” — Larry Page.
#
#Facts:
#
#    “Googol” is a 📘 mathematical term whose contents include a unit with 100 zeros. This is where the company name comes from.
#    Google constantly rents 🐐 goats for one purpose which is mowing the lawn. In such a way, the company adheres to the green initiative.
#    Surprising fact is that the first Google 🖥 computer storage consisted of the Lego constructor.
#



🤣 Smileys & Emotion


😈 Smiling Face With Horns Emoji
😎 Smiling Face With Sunglasses Emoji
💫 Dizzy Emoji
👻 Ghost Emoji
👹 Ogre Emoji
🙉 Hear-no-evil Monkey Emoji
👿 Angry Face With Horns Emoji
❤️ Red Heart Emoji
💩 Pile of Poo Emoji
👺 Goblin Emoji
💛 Yellow Heart Emoji
💕 Two Hearts Emoji
😬 Grimacing Face Emoji
😏 Smirking Face Emoji
😊 Smiling Face With Smiling Eyes Emoji
💯 Hundred Points Emoji
💥 Collision Emoji
👾 Alien Monster Emoji
💣 Bomb Emoji
💟 Heart Decoration Emoji
😂 Face With Tears of Joy Emoji
😍 Smiling Face With Heart-Eyes Emoji
🤔 Thinking Face Emoji
😘 Face Blowing a Kiss Emoji
🙄 Face With Rolling Eyes Emoji
😀 Grinning Face Emoji
😁 Beaming Face With Smiling Eyes Emoji
🤣 Rolling on the Floor Laughing Emoji
😃 Grinning Face With Big Eyes Emoji
😄 Grinning Face With Smiling Eyes Emoji
😅 Grinning Face With Sweat Emoji
😋 Face Savoring Food Emoji
😗 Kissing Face Emoji
😆 Grinning Squinting Face Emoji
😉 Winking Face Emoji
😙 Kissing Face With Smiling Eyes Emoji
😚 Kissing Face With Closed Eyes Emoji
☺️ Smiling Face Emoji
🙂 Slightly Smiling Face Emoji
🤗 Hugging Face Emoji
😐 Neutral Face Emoji
😑 Expressionless Face Emoji
😶 Face Without Mouth Emoji
😣 Persevering Face Emoji
😥 Sad But Relieved Face Emoji
😮 Face With Open Mouth Emoji
🤐 Zipper-Mouth Face Emoji
😯 Hushed Face Emoji
😪 Sleepy Face Emoji
😫 Tired Face Emoji
😴 Sleeping Face Emoji
😌 Relieved Face Emoji
😛 Face With Tongue Emoji
😜 Winking Face With Tongue Emoji
😝 Squinting Face With Tongue Emoji
🤤 Drooling Face Emoji
😒 Unamused Face Emoji
😓 Downcast Face With Sweat Emoji
😔 Pensive Face Emoji
😕 Confused Face Emoji
🙃 Upside-Down Face Emoji
☹️ Frowning Face Emoji
🤑 Money-Mouth Face Emoji
😲 Astonished Face Emoji
🙁 Slightly Frowning Face Emoji
😖 Confounded Face Emoji
😞 Disappointed Face Emoji
😟 Worried Face Emoji
😤 Face With Steam From Nose Emoji
😢 Crying Face Emoji
😭 Loudly Crying Face Emoji
😦 Frowning Face With Open Mouth Emoji
😧 Anguished Face Emoji
😨 Fearful Face Emoji
😩 Weary Face Emoji
😰 Anxious Face With Sweat Emoji
😱 Face Screaming in Fear Emoji
😳 Flushed Face Emoji
😵 Dizzy Face Emoji
😡 Pouting Face Emoji
😠 Angry Face Emoji
😷 Face With Medical Mask Emoji
🤒 Face With Thermometer Emoji
🤢 Nauseated Face Emoji
🤕 Face With Head-Bandage Emoji
🤧 Sneezing Face Emoji
😇 Smiling Face With Halo Emoji
🤠 Cowboy Hat Face Emoji
🤡 Clown Face Emoji
🤥 Lying Face Emoji
🤓 Nerd Face Emoji
💀 Skull Emoji
👽 Alien Emoji
🤖 Robot Emoji
😺 Grinning Cat Emoji
😸 Grinning Cat With Smiling Eyes Emoji
😹 Cat With Tears Of Joy Emoji
😻 Smiling Cat With Heart-Eyes Emoji
😼 Cat With Wry Smile Emoji
😽 Kissing Cat Emoji
🙀 Weary Cat Emoji
😿 Crying Cat Emoji
😾 Pouting Cat Emoji
💨 Dashing Away Emoji
🕳 Hole Emoji
💋 Kiss Mark Emoji
💌 Love Letter Emoji
🙈 See-No-Evil Monkey Emoji
☠️ Skull and Crossbones Emoji
🙊 Speak-No-Evil Monkey Emoji
💦 Sweat Droplets Emoji
👁️‍🗨️ Eye In Speech Bubble Emoji
💓 Beating Heart Emoji
💔 Broken Heart Emoji
💖 Sparkling Heart Emoji
💗 Growing Heart Emoji
💘 Heart With Arrow Emoji
💙 Blue Heart Emoji
💚 Green Heart Emoji
💜 Purple Heart Emoji
💝 Heart With Ribbon Emoji
💞 Revolving Hearts Emoji
💢 Anger Symbol Emoji
💤 Zzz Emoji
💬 Speech Balloon Emoji
💭 Thought Balloon Emoji
🖤 Black Heart Emoji
🗨 Left Speech Bubble Emoji
🗯 Right Anger Bubble Emoji
🧡 Orange Heart Emoji
❣️ Heart Exclamation Emoji
🤪 Zany Face Emoji
🤬 Face With Symbols On Mouth Emoji
🤯 Exploding Head Emoji
🥵 Hot Face Emoji
🥶 Cold Face Emoji
🤨 Face With Raised Eyebrow Emoji
🤩 Star-Struck Emoji
🥰 Smiling Face With Hearts Emoji
🤫 Shushing Face Emoji
🤭 Face With Hand Over Mouth Emoji
🥳 Partying Face Emoji
🥴 Woozy Face Emoji
🥺 Pleading Face Emoji
🧐 Face With Monocle Emoji
🤮 Face Vomiting Emoji
🥱 Yawning Face Emoji
🤎 Brown Heart Emoji
🤍 White Heart Emoji


🤷 People & Body


👀 Eyes Emoji
🕵 Detective Emoji
👆 Backhand Index Pointing Up Emoji
✌ Victory Hand Emoji
👶 Baby Emoji
💪 Flexed Biceps Emoji
👱 Person: Blond Hair Emoji
👏 Clapping Hands Emoji
👊 Oncoming Fist Emoji
🙏 Folded Hands Emoji
🚣 Person Rowing Boat Emoji
👸 Princess Emoji
🤷 Person Shrugging Emoji
👤 Bust in Silhouette Emoji
👦 Boy Emoji
👧 Girl Emoji
👨 Man Emoji
👩 Woman Emoji
👴 Old Man Emoji
👵 Old Woman Emoji
👨‍⚕️ ️Man Health Worker Emoji
👩‍⚕️ ️Woman Health Worker Emoji
👨‍🎓 Man Student Emoji
👩‍🎓 Woman Student Emoji
👨‍⚖️ ️Man Judge Emoji
👩‍⚖️ ️Woman Judge Emoji
👨‍🌾 Man Farmer Emoji
👩‍🌾 Woman Farmer Emoji
👨‍🍳 Man Cook Emoji
👩‍🍳 Woman Cook Emoji
👨‍🔧 Man Mechanic Emoji
👩‍🔧 Woman Mechanic Emoji
👨‍🏭 Man Factory Worker Emoji
👩‍🏭 Woman Factory Worker Emoji
👨‍💼 Man Office Worker Emoji
👩‍💼 Woman Office Worker Emoji
👨‍🔬 Man Scientist Emoji
👩‍🔬 Woman Scientist Emoji
👨‍💻 Man Technologist Emoji
👩‍💻 Woman Technologist Emoji
👨‍🎤 Man Singer Emoji
👩‍🎤 Woman Singer Emoji
👨‍🎨 Man Artist Emoji
👩‍🎨 Woman Artist Emoji
👨‍✈️ ️Man Pilot Emoji
👩‍✈️ ️Woman Pilot Emoji
👨‍🚀 Man Astronaut Emoji
👩‍🚀 Woman Astronaut Emoji
👨‍🚒 Man Firefighter Emoji
👩‍🚒 Woman Firefighter Emoji
👮 Police Officer Emoji
👮‍♂️ Man Police Officer Emoji
👮‍♀️ Woman Police Officer Emoji
🕵️‍♀️ Woman Detective Emoji
💂 Guard Emoji
💂‍♂️ Man Guard Emoji
💂‍♀️ Woman Guard Emoji
👷 Construction Worker Emoji
👷‍♂️ Man Construction Worker Emoji
👷‍♀️ Woman Construction Worker Emoji
🤴 Prince Emoji
👳 Person Wearing Turban Emoji
👳‍♀️ Woman Wearing Turban Emoji
👲 Person With Skullcap Emoji
👱‍♀️ Woman: Blond Hair Emoji
🗣 Speaking Head Emoji
💇‍♀️ Woman Getting Haircut Emoji
🤞 Crossed Fingers Emoji
👂 Ear Emoji
👁 Eye Emoji
👪 Family Emoji
👣 Footprints Emoji
🤝 Handshake Emoji
🏇 Horse Racing Emoji
🤛 Left-Facing Fist Emoji
🏌️‍♂️ Man Golfing Emoji
👄 Mouth Emoji
💅 Nail Polish Emoji
👃 Nose Emoji
👌 OK Hand Emoji
👐 Open Hands Emoji
🏌 Person Golfing Emoji
🛌 Person in Bed Emoji
🛀 Person Taking Bath Emoji
🤚 Raised Back of Hand Emoji
✊ Raised Fist Emoji
✋ Raised Hand Emoji
🙌 Raising Hands Emoji
🤜 Right-Facing Fist Emoji
🤘 Sign of the Horns Emoji
⛷ Skier Emoji
🏂 Snowboarder Emoji
👎 Thumbs Down Emoji
👍 Thumbs Up Emoji
👅 Tongue Emoji
🖖 Vulcan Salute Emoji
👋 Waving Hand Emoji
🏌️‍♀️ Woman Golfing Emoji
✍ Writing Hand Emoji
👼 Baby Angel Emoji
👇 Backhand Index Pointing Down Emoji
👈 Backhand Index Pointing Left Emoji
👉 Backhand Index Pointing Right Emoji
👰 Person With Veil Emoji
👥 Busts in Silhouette Emoji
💑 Couple With Heart Emoji
👨‍❤️‍👨 Couple With Heart: Man, Man Emoji
👩‍❤️‍👩 Couple With Heart: Woman, Woman Emoji
👨‍👦 Family: Man, Boy Emoji
👨‍👦‍👦 Family: Man, Boy, Boy Emoji
👨‍👧 Family: Man, Girl Emoji
👨‍👧‍👦 Family: Man, Girl, Boy Emoji
👨‍👧‍👧 Family: Man, Girl, Girl Emoji
👨‍👨‍👦 Family: Man, Man, Boy Emoji
👨‍👨‍👦‍👦 Family: Man, Man, Boy, Boy Emoji
👨‍👨‍👧 Family: Man, Man, Girl Emoji
👨‍👨‍👧‍👦 Family: Man, Man, Girl, Boy Emoji
👨‍👨‍👧‍👧 Family: Man, Man, Girl, Girl Emoji
👨‍👩‍👦 Family: Man, Woman, Boy Emoji
👨‍👩‍👦‍👦 Family: Man, Woman, Boy, Boy Emoji
👨‍👩‍👧 Family: Man, Woman, Girl Emoji
👨‍👩‍👧‍👦 Family: Man, Woman, Girl, Boy Emoji
👩‍👦 Family: Woman, Boy Emoji
👩‍👦‍👦 Family: Woman, Boy, Boy Emoji
👩‍👧 Family: Woman, Girl Emoji
👩‍👧‍👦 Family: Woman, Girl, Boy Emoji
👩‍👧‍👧 Family: Woman, Girl, Girl Emoji
👩‍👩‍👦 Family: Woman, Woman, Boy Emoji
👩‍👩‍👦‍👦 Family: Woman, Woman, Boy, Boy Emoji
👩‍👩‍👧 Family: Woman, Woman, Girl Emoji
👩‍👩‍👧‍👦 Family: Woman, Woman, Girl, Boy Emoji
☝ Index Pointing Up Emoji
💏 Kiss Emoji
👨‍❤️‍💋‍👨 Kiss: Man, Man Emoji
👩‍❤️‍💋‍👩 Kiss: Woman, Woman Emoji
👫 Woman And Man Holding Hands Emoji
🙇‍♂️ Man Bowing Emoji
🕺 Man Dancing Emoji
🤦‍♂️ Man Facepalming Emoji
🙍‍♂️ Man Frowning Emoji
🙅‍♂️ Man Gesturing NO Emoji
🙆‍♂️ Man Gesturing OK Emoji
💇‍♂️ Man Getting Haircut Emoji
💆‍♂️ Man Getting Massage Emoji
🕴 Person In Suit Levitating Emoji
🤵 Person In Tuxedo Emoji
🙎‍♂️ Man Pouting Emoji
🙋‍♂️ Man Raising Hand Emoji
🏃‍♂️ Man Running Emoji
🤷‍♂️ Man Shrugging Emoji
💁‍♂️ Man Tipping Hand Emoji
🚶‍♂️ Man Walking Emoji
🖕 Middle Finger Emoji
🤶 Mrs. Claus Emoji
👯 People With Bunny Ears Emoji
🙇 Person Bowing Emoji
🤦 Person Facepalming Emoji
🙍 Person Frowning Emoji
🙅 Person Gesturing NO Emoji
🙆 Person Gesturing OK Emoji
💇 Person Getting Haircut Emoji
💆 Person Getting Massage Emoji
🙎 Person Pouting Emoji
🙋 Person Raising Hand Emoji
🏃 Person Running Emoji
💁 Person Tipping Hand Emoji
🚶 Person Walking Emoji
🤰 Pregnant Woman Emoji
🖐 Hand With Fingers Splayed Emoji
🎅 Santa Claus Emoji
🤳 Selfie Emoji
👬 Men Holding Hands Emoji
👭 Women Holding Hands Emoji
🙇‍♀️ Woman Bowing Emoji
💃 Woman Dancing Emoji
🤦‍♀️ Woman Facepalming Emoji
🙍‍♀️ Woman Frowning Emoji
🙅‍♀️ Woman Gesturing NO Emoji
🙆‍♀️ Woman Gesturing OK Emoji
🤙 Call Me Hand Emoji
🤟 Love-You Gesture Emoji
🤲 Palms Up Together Emoji
🦴 Bone Emoji
🦵 Leg Emoji
🦶 Foot Emoji
🦷 Tooth Emoji
🧠 Brain Emoji
👨‍👩‍👧‍👧 Family: Man, Woman, Girl, Girl Emoji
👩‍👩‍👧‍👧 Family: Woman, Woman, Girl, Girl Emoji
👩‍❤️‍👨 Couple With Heart: Woman, Man Emoji
👩‍❤️‍💋‍👨 Kiss: Woman, Man Emoji
🧑 Person Emoji
🧒 Child Emoji
🧓 Older Person Emoji
🏃‍♀️ Woman Running Emoji
👯‍♀️ Women With Bunny Ears Emoji
👯‍♂️ Men With Bunny Ears Emoji
💆‍♀️ Woman Getting Massage Emoji
🚶‍♀️ Woman Walking Emoji
🧖 Person In Steamy Room Emoji
🧖‍♀️ Woman In Steamy Room Emoji
🧖‍♂️ Man In Steamy Room Emoji
🧗 Person Climbing Emoji
🧗‍♀️ Woman Climbing Emoji
🧗‍♂️ Man Climbing Emoji
🧘 Person In Lotus Position Emoji
🧘‍♀️ Woman In Lotus Position Emoji
🧘‍♂️ Man In Lotus Position Emoji
🦸 Superhero Emoji
🦸‍♀️ Woman Superhero Emoji
🦸‍♂️ Man Superhero Emoji
🦹 Supervillain Emoji
🦹‍♀️ Woman Supervillain Emoji
🦹‍♂️ Man Supervillain Emoji
🧙 Mage Emoji
🧙‍♀️ Woman Mage Emoji
🧙‍♂️ Man Mage Emoji
🧚 Fairy Emoji
🧚‍♀️ Woman Fairy Emoji
🧚‍♂️ Man Fairy Emoji
🧛 Vampire Emoji
🧛‍♀️ Woman Vampire Emoji
🧛‍♂️ Man Vampire Emoji
🧜 Merperson Emoji
🧜‍♀️ Mermaid Emoji
🧜‍♂️ Merman Emoji
🧝 Elf Emoji
🧝‍♀️ Woman Elf Emoji
🧝‍♂️ Man Elf Emoji
🧞 Genie Emoji
🧞‍♀️ Woman Genie Emoji
🧞‍♂️ Man Genie Emoji
🧟 Zombie Emoji
🧟‍♀️ Woman Zombie Emoji
🧟‍♂️ Man Zombie Emoji
💁‍♀️ Woman Tipping Hand Emoji
🙋‍♀️ Woman Raising Hand Emoji
🙎‍♀️ Woman Pouting Emoji
🤷‍♀️ Woman Shrugging Emoji
👨‍🏫 Man Teacher Emoji
👨‍🦰 Man: Red Hair Emoji
👨‍🦱 Man: Curly Hair Emoji
👨‍🦲 Man: Bald Emoji
👨‍🦳 Man: White Hair Emoji
👩‍🏫 Woman Teacher Emoji
👩‍🦰 Woman: Red Hair Emoji
👩‍🦱 Woman: Curly Hair Emoji
👩‍🦲 Woman: Bald Emoji
👩‍🦳 Woman: White Hair Emoji
👱‍♂️ Man: Blond Hair Emoji
👳‍♂️ Man Wearing Turban Emoji
🕵️‍♂️ Man Detective Emoji
🤱 Breast-Feeding Emoji
🧔 Man: Beard Emoji
🧕 Woman With Headscarf Emoji
🏄 Person Surfing Emoji
🏄‍♀️ Woman Surfing Emoji
🏄‍♂️ Man Surfing Emoji
🏊 Person Swimming Emoji
🏊‍♀️ Woman Swimming Emoji
🏊‍♂️ Man Swimming Emoji
🏋 Person Lifting Weights Emoji
🏋️‍♀️ Woman Lifting Weights Emoji
🏋️‍♂️ Man Lifting Weights Emoji
🚣‍♀️ Woman Rowing Boat Emoji
🚣‍♂️ Man Rowing Boat Emoji
🚴 Person Biking Emoji
🚴‍♀️ Woman Biking Emoji
🚴‍♂️ Man Biking Emoji
🚵 Person Mountain Biking Emoji
🚵‍♀️ Woman Mountain Biking Emoji
🚵‍♂️ Man Mountain Biking Emoji
🤸 Person Cartwheeling Emoji
🤸‍♀️ Woman Cartwheeling Emoji
🤸‍♂️ Man Cartwheeling Emoji
🤹 Person Juggling Emoji
🤹‍♀️ Woman Juggling Emoji
🤹‍♂️ Man Juggling Emoji
🤺 Person Fencing Emoji
🤼 People Wrestling Emoji
🤼‍♀️ Women Wrestling Emoji
🤼‍♂️ Men Wrestling Emoji
🤽 Person Playing Water Polo Emoji
🤽‍♀️ Woman Playing Water Polo Emoji
🤽‍♂️ Man Playing Water Polo Emoji
🤾 Person Playing Handball Emoji
🤾‍♀️ Woman Playing Handball Emoji
🤾‍♂️ Man Playing Handball Emoji
⛹ Person Bouncing Ball Emoji
⛹️‍♀️ Woman Bouncing Ball Emoji
⛹️‍♂️ Man Bouncing Ball Emoji
🤏 Pinching Hand Emoji
🦾 Mechanical Arm Emoji
🦿 Mechanical Leg Emoji
🦻 Ear With Hearing Aid Emoji
🧏 Deaf Person Emoji
🧏‍♂️ Deaf Man Emoji
🧏‍♀️ Deaf Woman Emoji
🧍 Person Standing Emoji
🧍‍♂️ Man Standing Emoji
🧍‍♀️ Woman Standing Emoji
🧎 Person Kneeling Emoji
🧎‍♂️ Man Kneeling Emoji
🧎‍♀️ Woman Kneeling Emoji
👨‍🦯 Man With White Cane Emoji
👩‍🦯 Woman With White Cane Emoji
👨‍🦼 Man In Motorized Wheelchair Emoji
👩‍🦼 Woman In Motorized Wheelchair Emoji
👨‍🦽 Man In Manual Wheelchair Emoji
👩‍🦽 Woman In Manual Wheelchair Emoji
🧑‍🤝‍🧑 People Holding Hands Emoji


🐼 Animals & Nature


🐼 Panda Emoji
🌵 Cactus Emoji
🐨 Koala Emoji
🐀 Rat Emoji
🌹 Rose Emoji
🐅 Tiger Emoji
🌷 Tulip Emoji
🐜 Ant Emoji
🐤 Baby Chick Emoji
🦇 Bat Emoji
🐻 Bear Emoji
🐦 Bird Emoji
🌼 Blossom Emoji
🐡 Blowfish Emoji
🐗 Boar Emoji
💐 Bouquet Emoji
🐛 Bug Emoji
🦋 Butterfly Emoji
🐪 Camel Emoji
🐈 Cat Emoji
🐱 Cat Face Emoji
🌸 Cherry Blossom Emoji
🐔 Chicken Emoji
🐿 Chipmunk Emoji
🐄 Cow Emoji
🐮 Cow Face Emoji
🐊 Crocodile Emoji
🌳 Deciduous Tree Emoji
🐕 Dog Emoji
🐶 Dog Face Emoji
🐬 Dolphin Emoji
🕊 Dove Emoji
🐉 Dragon Emoji
🐲 Dragon Face Emoji
🦆 Duck Emoji
🦅 Eagle Emoji
🐘 Elephant Emoji
🌲 Evergreen Tree Emoji
🐑 Ewe Emoji
🍂 Fallen Leaf Emoji
🐟 Fish Emoji
🍀 Four Leaf Clover Emoji
🦊 Fox Emoji
🐸 Frog Emoji
🐥 Front-Facing Baby Chick Emoji
🐐 Goat Emoji
🦍 Gorilla Emoji
🐹 Hamster Emoji
🐣 Hatching Chick Emoji
🌿 Herb Emoji
🌺 Hibiscus Emoji
🐝 Honeybee Emoji
🐎 Horse Emoji
🐴 Horse Face Emoji
🐞 Lady Beetle Emoji
🍃 Leaf Fluttering in Wind Emoji
🐆 Leopard Emoji
🦁 Lion Emoji
🦎 Lizard Emoji
🍁 Maple Leaf Emoji
🐒 Monkey Emoji
🐵 Monkey Face Emoji
🐁 Mouse Emoji
🐭 Mouse Face Emoji
🐙 Octopus Emoji
🦉 Owl Emoji
🐂 Ox Emoji
🌴 Palm Tree Emoji
🐾 Paw Prints Emoji
🐧 Penguin Emoji
🐖 Pig Emoji
🐷 Pig Face Emoji
🐽 Pig Nose Emoji
🐩 Poodle Emoji
🐇 Rabbit Emoji
🐰 Rabbit Face Emoji
🐏 Ram Emoji
🦏 Rhinoceros Emoji
🐓 Rooster Emoji
🏵 Rosette Emoji
🦂 Scorpion Emoji
🌱 Seedling Emoji
☘️ Shamrock Emoji
🌾 Sheaf of Rice Emoji
🐌 Snail Emoji
🐍 Snake Emoji
🕷 Spider Emoji
🕸 Spider Web Emoji
🐚 Spiral Shell Emoji
🐳 Spouting Whale Emoji
🌻 Sunflower Emoji
🐯 Tiger Face Emoji
🐠 Tropical Fish Emoji
🦃 Turkey Emoji
🐢 Turtle Emoji
🐫 Two-Hump Camel Emoji
🦄 Unicorn Emoji
🐃 Water Buffalo Emoji
🐋 Whale Emoji
💮 White Flower Emoji
🥀 Wilted Flower Emoji
🐺 Wolf Emoji
🦚 Peacock Emoji
🦜 Parrot Emoji
🦢 Swan Emoji
🦗 Cricket Emoji
🦟 Mosquito Emoji
🦠 Microbe Emoji
🦌 Deer Emoji
🦒 Giraffe Emoji
🦓 Zebra Emoji
🦔 Hedgehog Emoji
🦘 Kangaroo Emoji
🦙 Llama Emoji
🦛 Hippopotamus Emoji
🦝 Raccoon Emoji
🦡 Badger Emoji
🦈 Shark Emoji
🦕 Sauropod Emoji
🦖 T-Rex Emoji
🦧 Orangutan Emoji
🦮 Guide Dog Emoji
🐕‍🦺 Service Dog Emoji
🦥 Sloth Emoji
🦦 Otter Emoji
🦨 Skunk Emoji
🦩 Flamingo Emoji


🍕 Food & Drink


🍭 Lollipop Emoji
🍏 Green Apple Emoji
🎂 Birthday Cake Emoji
🥑 Avocado Emoji
🍳 Cooking Emoji
🍌 Banana Emoji
🍞 Bread Emoji
🍰 Shortcake Emoji
🍒 Cherries Emoji
🍓 Strawberry Emoji
🍐 Pear Emoji
🍕 Pizza Emoji
🍋 Lemon Emoji
🌰 Chestnut Emoji
🏺 Amphora Emoji
🍼 Baby Bottle Emoji
🥓 Bacon Emoji
🥖 Baguette Bread Emoji
🍺 Beer Mug Emoji
🍱 Bento Box Emoji
🍾 Bottle With Popping Cork Emoji
🌯 Burrito Emoji
🍬 Candy Emoji
🥕 Carrot Emoji
🧀 Cheese Wedge Emoji
🍫 Chocolate Bar Emoji
🍻 Clinking Beer Mugs Emoji
🥂 Clinking Glasses Emoji
🍸 Cocktail Glass Emoji
🍚 Cooked Rice Emoji
🍪 Cookie Emoji
🦀 Crab Emoji
🥐 Croissant Emoji
🥒 Cucumber Emoji
🍛 Curry Rice Emoji
🍮 Custard Emoji
🍡 Dango Emoji
🍩 Doughnut Emoji
🌽 Ear of Corn Emoji
🍆 Eggplant Emoji
🍥 Fish Cake With Swirl Emoji
🍴 Fork and Knife Emoji
🍽 Fork and Knife With Plate Emoji
🍟 French Fries Emoji
🍤 Fried Shrimp Emoji
🥛 Glass of Milk Emoji
🍇 Grapes Emoji
🥗 Green Salad Emoji
🍔 Hamburger Emoji
🍯 Honey Pot Emoji
☕ Hot Beverage Emoji
🌭 Hot Dog Emoji
🌶 Hot Pepper Emoji
🍨 Ice Cream Emoji
🔪 Kitchen Knife Emoji
🥝 Kiwi Fruit Emoji
🍖 Meat on Bone Emoji
🍈 Melon Emoji
🍄 Mushroom Emoji
🍢 Oden Emoji
🥞 Pancakes Emoji
🍑 Peach Emoji
🥜 Peanuts Emoji
🍿 Popcorn Emoji
🍲 Pot of Food Emoji
🥔 Potato Emoji
🍗 Poultry Leg Emoji
🍎 Red Apple Emoji
🍙 Rice Ball Emoji
🍘 Rice Cracker Emoji
🍠 Roasted Sweet Potato Emoji
🍶 Sake Emoji
🍧 Shaved Ice Emoji
🦐 Shrimp Emoji
🍦 Soft Ice Cream Emoji
🍝 Spaghetti Emoji
🥄 Spoon Emoji
🦑 Squid Emoji
🍜 Steaming Bowl Emoji
🍣 Sushi Emoji
🌮 Taco Emoji
🍊 Tangerine Emoji
🍵 Teacup Without Handle Emoji
🍅 Tomato Emoji
🍹 Tropical Drink Emoji
🥃 Tumbler Glass Emoji
🍉 Watermelon Emoji
🍷 Wine Glass Emoji
🦞 Lobster Emoji
🥢 Chopsticks Emoji
🥤 Cup With Straw Emoji
🥟 Dumpling Emoji
🥠 Fortune Cookie Emoji
🥡 Takeout Box Emoji
🥮 Moon Cake Emoji
🍍 Pineapple Emoji
🥥 Coconut Emoji
🥭 Mango Emoji
🥘 Shallow Pan Of Food Emoji
🥙 Stuffed Flatbread Emoji
🥚 Egg Emoji
🥣 Bowl With Spoon Emoji
🥨 Pretzel Emoji
🥩 Cut Of Meat Emoji
🥪 Sandwich Emoji
🥫 Canned Food Emoji
🥯 Bagel Emoji
🧂 Salt Emoji
🥧 Pie Emoji
🧁 Cupcake Emoji
🥦 Broccoli Emoji
🥬 Leafy Green Emoji
🧄 Garlic Emoji
🧅 Onion Emoji
🧇 Waffle Emoji
🧆 Falafel Emoji
🧈 Butter Emoji
🦪 Oyster Emoji
🧃 Beverage Box Emoji
🧉 Mate Emoji
🧊 Ice Emoji


💯 Symbols


🔵 Blue Circle Emoji
⚪ White Circle Emoji
♈ Aries Emoji
♉ Taurus Emoji
♊ Gemini Emoji
♋ Cancer Emoji
♌ Leo Emoji
♍ Virgo Emoji
♎ Libra Emoji
♏ Scorpio Emoji
♐ Sagittarius Emoji
♑ Capricorn Emoji
♒ Aquarius Emoji
♓ Pisces Emoji
🔂 Repeat Single Button Emoji
🔁 Repeat Button Emoji
🔄 Counterclockwise Arrows Button Emoji
🔠 Input Latin Uppercase Emoji
⚜️ Fleur-de-lis Emoji
⬆️ Up Arrow Emoji
🛄 Baggage Claim Emoji
🛃 Customs Emoji
🛅 Left Luggage Emoji
🛂 Passport Control Emoji
🅰️ A Button (Blood Type) Emoji
🅱️ B Button (Blood Type) Emoji
🅾️ O Button (Blood Type) Emoji
🅿️ P Button Emoji
🆎 AB Button (Blood Type) Emoji
🆑 CL Button Emoji
🆒 COOL Button Emoji
🆓 FREE Button Emoji
🆔 ID Button Emoji
🆕 NEW Button Emoji
🆖 NG Button Emoji
🆗 OK Button Emoji
🆘 SOS Button Emoji
🆙 UP! Button Emoji
🆚 VS Button Emoji
🈁 Japanese here Button Emoji
🈂️ Japanese service Charge Button Emoji
🈚 Japanese free Of Charge Button Emoji
🈯 Japanese reserved Button Emoji
🈲 Japanese prohibited Button Emoji
🈳 Japanese vacancy Button Emoji
🈴 Japanese passing Grade Button Emoji
🈵 Japanese no Vacancy Button Emoji
🈶 Japanese not Free Of Charge Button Emoji
🈷️ Japanese monthly Amount Button Emoji
🈸 Japanese application Button Emoji
🈹 Japanese discount Button Emoji
🈺 Japanese open For Business Button Emoji
🉐 Japanese bargain Button Emoji
🉑 Japanese acceptable Button Emoji
🔡 Input Latin Lowercase Emoji
🔢 Input Numbers Emoji
🔣 Input Symbols Emoji
🔤 Input Latin Letters Emoji
ℹ️ Information Emoji
Ⓜ️ Circled M Emoji
㊗️ Japanese congratulations Button Emoji
㊙️ Japanese secret Button Emoji
🔃 Clockwise Vertical Arrows Emoji
🔙 BACK Arrow Emoji
🔚 END Arrow Emoji
🔛 ON! Arrow Emoji
🔜 SOON Arrow Emoji
🔝 TOP Arrow Emoji
↔ Left-Right Arrow Emoji
↕ Up-Down Arrow Emoji
↖️ Up-Left Arrow Emoji
↗️ Up-Right Arrow Emoji
↘️ Down-Right Arrow Emoji
↙️ Down-Left Arrow Emoji
↩️ Right Arrow Curving Left Emoji
↪️ Left Arrow Curving Right Emoji
➡️ Right Arrow Emoji
⤴️ Right Arrow Curving Up Emoji
⤵️ Right Arrow Curving Down Emoji
⬅️ Left Arrow Emoji
⬇️ Down Arrow Emoji
🎦 Cinema Emoji
📳 Vibration Mode Emoji
📴 Mobile Phone Off Emoji
📶 Antenna Bars Emoji
🔀 Shuffle Tracks Button Emoji
🔅 Dim Button Emoji
🔆 Bright Button Emoji
🔼 Upwards Button Emoji
🔽 Downwards Button Emoji
⏏️ Eject Button Emoji
⏩ Fast-Forward Button Emoji
⏪ Fast Reverse Button Emoji
⏫ Fast Up Button Emoji
⏬ Fast Down Button Emoji
⏭ Next Track Button Emoji
⏮ Last Track Button Emoji
⏯ Play Or Pause Button Emoji
⏸ Pause Button Emoji
⏹ Stop Button Emoji
⏺ Record Button Emoji
▶️ Play Button Emoji
◀️ Reverse Button Emoji
💠 Diamond With A Dot Emoji
🔘 Radio Button Emoji
🔲 Black Square Button Emoji
🔳 White Square Button Emoji
🔴 Red Circle Emoji
🔶 Large Orange Diamond Emoji
🔷 Large Blue Diamond Emoji
🔸 Small Orange Diamond Emoji
🔹 Small Blue Diamond Emoji
🔺 Red Triangle Pointed Up Emoji
🔻 Red Triangle Pointed Down Emoji
▪ Black Small Square Emoji
▫ White Small Square Emoji
◻️ White Medium Square Emoji
◼️ Black Medium Square Emoji
◽ White Medium-Small Square Emoji
◾ Black Medium-Small Square Emoji
⚫ Black Circle Emoji
⬛ Black Large Square Emoji
⬜ White Large Square Emoji
#️⃣ Keycap: # Emoji
*️⃣ Keycap: * Emoji
0️⃣ Keycap: 0 Emoji
1️⃣ Keycap: 1 Emoji
2️⃣ Keycap: 2 Emoji
3️⃣ Keycap: 3 Emoji
4️⃣ Keycap: 4 Emoji
5️⃣ Keycap: 5 Emoji
6️⃣ Keycap: 6 Emoji
7️⃣ Keycap: 7 Emoji
8️⃣ Keycap: 8 Emoji
9️⃣ Keycap: 9 Emoji
🔟 Keycap: 10 Emoji
💱 Currency Exchange Emoji
💲 Heavy Dollar Sign Emoji
📛 Name Badge Emoji
🔰 Japanese Symbol For Beginner Emoji
🔱 Trident Emblem Emoji
‼ Double Exclamation Mark Emoji
⁉️ Exclamation Question Mark Emoji
™ Trade Mark Emoji
☑️ Check Box With Check Emoji
♀ Female Sign Emoji
♂ Male Sign Emoji
♻️ Recycling Symbol Emoji
♾️ Infinity Emoji
⚕️ Medical Symbol Emoji
✅ Check Mark Button Emoji
✔️ Check Mark Emoji
✖️ Multiply Emoji
✳️ Eight-Spoked Asterisk Emoji
✴️ Eight-Pointed Star Emoji
❇️ Sparkle Emoji
❌ Cross Mark Emoji
❎ Cross Mark Button Emoji
❓ Question Mark Emoji
❔ White Question Mark Emoji
❕ White Exclamation Mark Emoji
❗ Exclamation Mark Emoji
➕ Plus Emoji
➖ Minus Emoji
➗ Divide Emoji
➰ Curly Loop Emoji
➿ Double Curly Loop Emoji
⭕ Hollow Red Circle Emoji
〰️ Wavy Dash Emoji
〽️ Part Alternation Mark Emoji
🔯 Dotted Six-Pointed Star Emoji
🕉 Om Emoji
🕎 Menorah Emoji
🛐 Place Of Worship Emoji
☦️ Orthodox Cross Emoji
☪️ Star And Crescent Emoji
☮️ Peace Symbol Emoji
☯️ Yin Yang Emoji
☸️ Wheel Of Dharma Emoji
⚛️ Atom Symbol Emoji
✝️ Latin Cross Emoji
✡️ Star Of David Emoji
🏧 ATM Sign Emoji
🚮 Litter In Bin Sign Emoji
🚰 Potable Water Emoji
🚹 Men s Room Emoji
🚺 Women s Room Emoji
🚻 Restroom Emoji
🚼 Baby Symbol Emoji
🚾 Water Closet Emoji
♿ Wheelchair Symbol Emoji
📵 No Mobile Phones Emoji
🔞 No One Under Eighteen Emoji
🚫 Prohibited Emoji
🚭 No Smoking Emoji
🚯 No Littering Emoji
🚱 Non-Potable Water Emoji
🚳 No Bicycles Emoji
🚷 No Pedestrians Emoji
🚸 Children Crossing Emoji
☢️ Radioactive Emoji
☣️ Biohazard Emoji
⚠️ Warning Emoji
⛔ No Entry Emoji
⛎ Ophiuchus Emoji
🟠 Orange Circle Emoji
🟡 Yellow Circle Emoji
🟢 Green Circle Emoji
🟣 Purple Circle Emoji
🟤 Brown Circle Emoji
🟥 Red Square Emoji
🟧 Orange Square Emoji
🟨 Yellow Square Emoji
🟩 Green Square Emoji
🟦 Blue Square Emoji
🟪 Purple Square Emoji
🟫 Brown Square Emoji


🌇 Travel & Places


🌎 Globe Showing Americas Emoji
🌟 Glowing Star Emoji
🚀 Rocket Emoji
🌞 Sun With Face Emoji
❄️ Snowflake Emoji
🌈 Rainbow Emoji
🌜 Last Quarter Moon Face Emoji
🔥 Fire Emoji
⌛ Hourglass Done Emoji
🚘 Oncoming Automobile Emoji
🌙 Crescent Moon Emoji
⭐ Star Emoji
🚨 Police Car Light Emoji
🚡 Aerial Tramway Emoji
✈️ Airplane Emoji
🛬 Airplane Arrival Emoji
🛫 Airplane Departure Emoji
⏰ Alarm Clock Emoji
🚑 Ambulance Emoji
⚓ Anchor Emoji
🚛 Articulated Lorry Emoji
🚗 Automobile Emoji
🏦 Bank Emoji
💈 Barber Pole Emoji
🏖 Beach With Umbrella Emoji
🛎 Bellhop Bell Emoji
🚲 Bicycle Emoji
🌉 Bridge at Night Emoji
🏗 Building Construction Emoji
🚌 Bus Emoji
🚏 Bus Stop Emoji
🏕 Camping Emoji
🎠 Carousel Horse Emoji
🏰 Castle Emoji
⛪ Church Emoji
🏙 Cityscape Emoji
🌆 Cityscape at Dusk Emoji
🏛 Classical Building Emoji
🌂 Closed Umbrella Emoji
☁️ Cloud Emoji
🌩 Cloud With Lightning Emoji
⛈ Cloud With Lightning and Rain Emoji
🌧 Cloud With Rain Emoji
🌨 Cloud With Snow Emoji
☄️ Comet Emoji
🚧 Construction Emoji
🏪 Convenience Store Emoji
🚚 Delivery Truck Emoji
🏬 Department Store Emoji
🏚 Derelict House Emoji
🏜 Desert Emoji
🏝 Desert Island Emoji
💧 Droplet Emoji
🏭 Factory Emoji
🎡 Ferris Wheel Emoji
⛴ Ferry Emoji
🚒 Fire Engine Emoji
🌓 First Quarter Moon Emoji
🌛 First Quarter Moon Face Emoji
🌫 Fog Emoji
🌁 Foggy Emoji
⛲ Fountain Emoji
⛽ Fuel Pump Emoji
🌕 Full Moon Emoji
🌝 Full Moon Face Emoji
🌏 Globe Showing Asia-Australia Emoji
🌍 Globe Showing Europe-Africa Emoji
🌐 Globe With Meridians Emoji
🚁 Helicopter Emoji
⚡ High Voltage Emoji
🚄 High-Speed Train Emoji
🚅 Bullet Train Emoji
🚥 Horizontal Traffic Light Emoji
🏥 Hospital Emoji
🏨 Hotel Emoji
⏳ Hourglass Not Done Emoji
🏘 Houses Emoji
🏠 House Emoji
🏡 House With Garden Emoji
🏯 Japanese Castle Emoji
🏣 Japanese Post Office Emoji
🕋 Kaaba Emoji
🛴 Kick Scooter Emoji
🌗 Last Quarter Moon Emoji
🚈 Light Rail Emoji
🚂 Locomotive Emoji
🏩 Love Hotel Emoji
🕰 Mantelpiece Clock Emoji
🗾 Map of Japan Emoji
🚇 Metro Emoji
🌌 Milky Way Emoji
🚐 Minibus Emoji
🚝 Monorail Emoji
🕌 Mosque Emoji
🛥 Motor Boat Emoji
🛵 Motor Scooter Emoji
🏍 Motorcycle Emoji
🗻 Mount Fuji Emoji
⛰ Mountain Emoji
🚠 Mountain Cableway Emoji
🚞 Mountain Railway Emoji
🏞 National Park Emoji
🌑 New Moon Emoji
🌚 New Moon Face Emoji
🌃 Night With Stars Emoji
🏢 Office Building Emoji
🚍 Oncoming Bus Emoji
🚔 Oncoming Police Car Emoji
🚖 Oncoming Taxi Emoji
🛳 Passenger Ship Emoji
🚓 Police Car Emoji
🏤 Post Office Emoji
🏎 Racing Car Emoji
🚃 Railway Car Emoji
🛤 Railway Track Emoji
🎢 Roller Coaster Emoji
⛵ Sailboat Emoji
🛰 Satellite Emoji
🏫 School Emoji
💺 Seat Emoji
⛩ Shinto Shrine Emoji
🚢 Ship Emoji
🌠 Shooting Star Emoji
🛩 Small Airplane Emoji
🏔 Snow-Capped Mountain Emoji
☃️ Snowman Emoji
⛄ Snowman Without Snow Emoji
🚤 Speedboat Emoji
🏟 Stadium Emoji
🚉 Station Emoji
🗽 Statue of Liberty Emoji
⏱ Stopwatch Emoji
☀️ Sun Emoji
⛅ Sun Behind Cloud Emoji
🌥 Sun Behind Large Cloud Emoji
🌦 Sun Behind Rain Cloud Emoji
🌤 Sun Behind Small Cloud Emoji
🌅 Sunrise Emoji
🌄 Sunrise Over Mountains Emoji
🌇 Sunset Emoji
🚟 Suspension Railway Emoji
🕍 Synagogue Emoji
🚕 Taxi Emoji
⛺ Tent Emoji
🌡 Thermometer Emoji
⏲ Timer Clock Emoji
🗼 Tokyo Tower Emoji
🌪 Tornado Emoji
🚜 Tractor Emoji
🚆 Train Emoji
🚊 Tram Emoji
🚋 Tram Car Emoji
🚎 Trolleybus Emoji
☂️ Umbrella Emoji
⛱ Umbrella on Ground Emoji
☔ Umbrella With Rain Drops Emoji
🚦 Vertical Traffic Light Emoji
🌋 Volcano Emoji
🌘 Waning Crescent Moon Emoji
🌖 Waning Gibbous Moon Emoji
⌚ Watch Emoji
🌊 Water Wave Emoji
🌒 Waxing Crescent Moon Emoji
🌔 Waxing Gibbous Moon Emoji
💒 Wedding Emoji
🌬 Wind Face Emoji
🗺 World Map Emoji
🧳 Luggage Emoji
🧱 Brick Emoji
🧭 Compass Emoji
🎪 Circus Tent Emoji
♨️ Hot Springs Emoji
🌀 Cyclone Emoji
🕐 One O clock Emoji
🕑 Two O clock Emoji
🕒 Three O clock Emoji
🕓 Four O clock Emoji
🕔 Five O clock Emoji
🕕 Six O clock Emoji
🕖 Seven O clock Emoji
🕗 Eight O clock Emoji
🕘 Nine O clock Emoji
🕙 Ten O clock Emoji
🕚 Eleven O clock Emoji
🕛 Twelve O clock Emoji
🕜 One-Thirty Emoji
🕝 Two-Thirty Emoji
🕞 Three-Thirty Emoji
🕟 Four-Thirty Emoji
🕠 Five-Thirty Emoji
🕡 Six-Thirty Emoji
🕢 Seven-Thirty Emoji
🕣 Eight-Thirty Emoji
🕤 Nine-Thirty Emoji
🕥 Ten-Thirty Emoji
🕦 Eleven-Thirty Emoji
🕧 Twelve-Thirty Emoji
🛸 Flying Saucer Emoji
🚙 Sport Utility Vehicle Emoji
🛑 Stop Sign Emoji
🛢 Oil Drum Emoji
🛣 Motorway Emoji
🛹 Skateboard Emoji
🛶 Canoe Emoji
🛕 Hindu Temple Emoji
🦽 Manual Wheelchair Emoji
🦼 Motorized Wheelchair Emoji
🛺 Auto Rickshaw Emoji
🪂 Parachute Emoji
🪐 Ringed Planet Emoji


📮 Objects


💽 Computer Disk Emoji
🔗 Link Emoji
☎️ Telephone Emoji
📧 E-mail Emoji
📼 Videocassette Emoji
🎥 Movie Camera Emoji
📹 Video Camera Emoji
🔦 Flashlight Emoji
🔎 Magnifying Glass Tilted Right Emoji
🔬 Microscope Emoji
📻 Radio Emoji
🎬 Clapper Board Emoji
📺 Television Emoji
📠 Fax Machine Emoji
👑 Crown Emoji
💵 Dollar Banknote Emoji
📀 DVD Emoji
🎧 Headphone Emoji
👠 High-heeled Shoe Emoji
🔑 Key Emoji
💄 Lipstick Emoji
💊 Pill Emoji
🗳 Ballot Box With Ballot Emoji
📊 Bar Chart Emoji
🛁 Bathtub Emoji
🔋 Battery Emoji
🛏 Bed Emoji
👙 Bikini Emoji
✒️ Black Nib Emoji
📘 Blue Book Emoji
🔖 Bookmark Emoji
📑 Bookmark Tabs Emoji
📚 Books Emoji
💼 Briefcase Emoji
📅 Calendar Emoji
📷 Camera Emoji
📸 Camera With Flash Emoji
🕯 Candle Emoji
🗃 Card File Box Emoji
📇 Card Index Emoji
🗂 Card Index Dividers Emoji
📉 Chart Decreasing Emoji
📈 Chart Increasing Emoji
📋 Clipboard Emoji
📕 Closed Book Emoji
📪 Closed Mailbox With Lowered Flag Emoji
📫 Closed Mailbox With Raised Flag Emoji
👝 Clutch Bag Emoji
🖱 Computer Mouse Emoji
🎛 Control Knobs Emoji
🛋 Couch and Lamp Emoji
🖍 Crayon Emoji
💳 Credit Card Emoji
🖥 Desktop Computer Emoji
🚪 Door Emoji
👗 Dress Emoji
🔌 Electric Plug Emoji
✉️ Envelope Emoji
📩 Envelope With Arrow Emoji
💶 Euro Banknote Emoji
🗄 File Cabinet Emoji
📁 File Folder Emoji
🎞 Film Frames Emoji
📽 Film Projector Emoji
💾 Floppy Disk Emoji
🖋 Fountain Pen Emoji
💎 Gem Stone Emoji
👓 Glasses Emoji
🎓 Graduation Cap Emoji
📗 Green Book Emoji
🔨 Hammer Emoji
⚒️ Hammer and Pick Emoji
👜 Handbag Emoji
📥 Inbox Tray Emoji
📨 Incoming Envelope Emoji
👖 Jeans Emoji
⌨️ Keyboard Emoji
👘 Kimono Emoji
🏷 Label Emoji
💻 Laptop Emoji
🔍 Magnifying Glass Tilted Left Emoji
🎚 Level Slider Emoji
💡 Light Bulb Emoji
🖇 Linked Paperclips Emoji
🔒 Locked Emoji
🔐 Locked With Key Emoji
🔏 Locked With Pen Emoji
👞 Man s Shoe Emoji
📝 Memo Emoji
🗿 Moai Emoji
📱 Mobile Phone Emoji
📲 Mobile Phone With Arrow Emoji
💰 Money Bag Emoji
💸 Money With Wings Emoji
👔 Necktie Emoji
📰 Newspaper Emoji
📓 Notebook Emoji
📔 Notebook With Decorative Cover Emoji
🗝 Old Key Emoji
📖 Open Book Emoji
📂 Open File Folder Emoji
📭 Open Mailbox With Lowered Flag Emoji
📬 Open Mailbox With Raised Flag Emoji
💿 Optical Disk Emoji
📙 Orange Book Emoji
📤 Outbox Tray Emoji
📦 Package Emoji
📄 Page Facing Up Emoji
📃 Page With Curl Emoji
📟 Pager Emoji
🖌 Paintbrush Emoji
📎 Paperclip Emoji
🖊 Pen Emoji
✏️ Pencil Emoji
⛏ Pick Emoji
📯 Postal Horn Emoji
📮 Postbox Emoji
💷 Pound Banknote Emoji
📿 Prayer Beads Emoji
🖨 Printer Emoji
👛 Purse Emoji
📌 Pushpin Emoji
🏮 Red Paper Lantern Emoji
⛑ Rescue Worker s Helmet Emoji
💍 Ring Emoji
🗞 Rolled-Up Newspaper Emoji
📍 Round Pushpin Emoji
👟 Running Shoe Emoji
📡 Satellite Antenna Emoji
🎒 Backpack Emoji
✂️ Scissors Emoji
📜 Scroll Emoji
🛍 Shopping Bags Emoji
🚿 Shower Emoji
🗓 Spiral Calendar Emoji
🗒 Spiral Notepad Emoji
📏 Straight Ruler Emoji
🎙 Studio Microphone Emoji
🕶 Sunglasses Emoji
👕 T-Shirt Emoji
📆 Tear-Off Calendar Emoji
📞 Telephone Receiver Emoji
🔭 Telescope Emoji
🚽 Toilet Emoji
🎩 Top Hat Emoji
🖲 Trackball Emoji
📐 Triangular Ruler Emoji
🔓 Unlocked Emoji
🗑 Wastebasket Emoji
👢 Woman s Boot Emoji
👚 Woman s Clothes Emoji
👒 Woman s Hat Emoji
👡 Woman s Sandal Emoji
💴 Yen Banknote Emoji
📒 Ledger Emoji
🥼 Lab Coat Emoji
🥽 Goggles Emoji
🥾 Hiking Boot Emoji
🥿 Flat Shoe Emoji
🧢 Billed Cap Emoji
🧣 Scarf Emoji
🧤 Gloves Emoji
🧥 Coat Emoji
🧦 Socks Emoji
🧮 Abacus Emoji
🛒 Shopping Cart Emoji
🧯 Fire Extinguisher Emoji
🧴 Lotion Bottle Emoji
🧷 Safety Pin Emoji
🧹 Broom Emoji
🧺 Basket Emoji
🧻 Roll Of Paper Emoji
🧼 Soap Emoji
🧽 Sponge Emoji
💉 Syringe Emoji
💹 Chart Increasing With Yen Emoji
🧾 Receipt Emoji
🎤 Microphone Emoji
🎵 Musical Note Emoji
🎶 Musical Notes Emoji
🎼 Musical Score Emoji
🎷 Saxophone Emoji
🎸 Guitar Emoji
🎹 Musical Keyboard Emoji
🎺 Trumpet Emoji
🎻 Violin Emoji
🥁 Drum Emoji
🚬 Cigarette Emoji
⚰️ Coffin Emoji
⚱️ Funeral Urn Emoji
🧪 Test Tube Emoji
🧫 Petri Dish Emoji
🧬 DNA Emoji
⚗️ Alembic Emoji
📢 Loudspeaker Emoji
📣 Megaphone Emoji
🔇 Muted Speaker Emoji
🔈 Speaker Low Volume Emoji
🔉 Speaker Medium Volume Emoji
🔊 Speaker High Volume Emoji
🔔 Bell Emoji
🔕 Bell With Slash Emoji
🏹 Bow And Arrow Emoji
🔧 Wrench Emoji
🔩 Nut And Bolt Emoji
🔫 Pistol Emoji
🗜 Clamp Emoji
🗡 Dagger Emoji
🛠 Hammer And Wrench Emoji
🛡 Shield Emoji
🧰 Toolbox Emoji
🧲 Magnet Emoji
⚔️ Crossed Swords Emoji
⚖️ Balance Scale Emoji
⚙️ Gear Emoji
⛓ Chains Emoji
🦺 Safety Vest Emoji
🥻 Sari Emoji
🩱 One-Piece Swimsuit Emoji
🩲 Briefs Emoji
🩳 Shorts Emoji
🩰 Ballet Shoes Emoji
🪕 Banjo Emoji
🪔 Diya Lamp Emoji
🪓 Axe Emoji
🦯 White Cane Emoji
🩸 Drop Of Blood Emoji
🩹 Adhesive Bandage Emoji
🩺 Stethoscope Emoji
🪑 Chair Emoji
🪒 Razor Emoji


🎈 Activities


✨ Sparkles Emoji
🎆 Fireworks Emoji
🎨 Artist Palette Emoji
🎈 Balloon Emoji
⚾ Baseball Emoji
🎲 Game Die Emoji
🎀 Ribbon Emoji
🎏 Carp Streamer Emoji
🎄 Christmas Tree Emoji
🎊 Confetti Ball Emoji
🖼 Framed Picture Emoji
🎎 Japanese Dolls Emoji
🕹 Joystick Emoji
🎑 Moon Viewing Ceremony Emoji
🎉 Party Popper Emoji
🎍 Pine Decoration Emoji
🎇 Sparkler Emoji
🎋 Tanabata Tree Emoji
🎐 Wind Chime Emoji
🎁 Wrapped Gift Emoji
🎭 Performing Arts Emoji
🧵 Thread Emoji
🧶 Yarn Emoji
🎖 Military Medal Emoji
🏅 Sports Medal Emoji
🏆 Trophy Emoji
🥇 1st Place Medal Emoji
🥈 2nd Place Medal Emoji
🥉 3rd Place Medal Emoji
🎃 Jack-O-Lantern Emoji
🎗 Reminder Ribbon Emoji
🎟 Admission Tickets Emoji
🎫 Ticket Emoji
🧧 Red Envelope Emoji
🧨 Firecracker Emoji
🀄 Mahjong Red Dragon Emoji
🃏 Joker Emoji
🎮 Video Game Emoji
🎯 Direct Hit Emoji
🎰 Slot Machine Emoji
🎱 Pool 8 Ball Emoji
🎴 Flower Playing Cards Emoji
🔮 Crystal Ball Emoji
🧩 Puzzle Piece Emoji
🧸 Teddy Bear Emoji
🧿 Nazar Amulet Emoji
♟️ Chess Pawn Emoji
♠️ Spade Suit Emoji
♣️ Club Suit Emoji
♥️ Heart Suit Emoji
♦️ Diamond Suit Emoji
🎣 Fishing Pole Emoji
🎳 Bowling Emoji
🎽 Running Shirt Emoji
🎾 Tennis Emoji
🎿 Skis Emoji
🏀 Basketball Emoji
🏈 American Football Emoji
🏉 Rugby Football Emoji
🏏 Cricket Game Emoji
🏐 Volleyball Emoji
🏑 Field Hockey Emoji
🏒 Ice Hockey Emoji
🏓 Ping Pong Emoji
🏸 Badminton Emoji
🛷 Sled Emoji
🥅 Goal Net Emoji
🥊 Boxing Glove Emoji
🥋 Martial Arts Uniform Emoji
🥌 Curling Stone Emoji
🥍 Lacrosse Emoji
🥎 Softball Emoji
🥏 Flying Disc Emoji
⚽ Soccer Ball Emoji
⛳ Flag In Hole Emoji
⛸ Ice Skate Emoji
🤿 Diving Mask Emoji
🪀 Yo-Yo Emoji
🪁 Kite Emoji


🇺🇸 Flags


🏁 Chequered Flag Emoji
🇺🇸 Flag: United States Emoji
🇦🇨 Flag: Ascension Island Emoji
🇦🇩 Flag: Andorra Emoji
🇦🇪 Flag: United Arab Emirates Emoji
🇦🇫 Flag: Afghanistan Emoji
🇦🇬 Flag: Antigua & Barbuda Emoji
🇦🇮 Flag: Anguilla Emoji
🇦🇱 Flag: Albania Emoji
🇦🇲 Flag: Armenia Emoji
🇦🇴 Flag: Angola Emoji
🇦🇶 Flag: Antarctica Emoji
🇦🇷 Flag: Argentina Emoji
🇦🇸 Flag: American Samoa Emoji
🇦🇹 Flag: Austria Emoji
🇦🇺 Flag: Australia Emoji
🇦🇼 Flag: Aruba Emoji
🇦🇽 Flag: Åland Islands Emoji
🇦🇿 Flag: Azerbaijan Emoji
🇧🇦 Flag: Bosnia & Herzegovina Emoji
🇧🇧 Flag: Barbados Emoji
🇧🇩 Flag: Bangladesh Emoji
🇧🇪 Flag: Belgium Emoji
🇧🇫 Flag: Burkina Faso Emoji
🇧🇬 Flag: Bulgaria Emoji
🇧🇭 Flag: Bahrain Emoji
🇧🇮 Flag: Burundi Emoji
🇧🇯 Flag: Benin Emoji
🇧🇱 Flag: St. Barthélemy Emoji
🇧🇲 Flag: Bermuda Emoji
🇧🇳 Flag: Brunei Emoji
🇧🇴 Flag: Bolivia Emoji
🇧🇶 Flag: Caribbean Netherlands Emoji
🇧🇷 Flag: Brazil Emoji
🇧🇸 Flag: Bahamas Emoji
🇧🇹 Flag: Bhutan Emoji
🇧🇻 Flag: Bouvet Island Emoji
🇧🇼 Flag: Botswana Emoji
🇧🇾 Flag: Belarus Emoji
🇧🇿 Flag: Belize Emoji
🇨🇦 Flag: Canada Emoji
🇨🇨 Flag: Cocos (Keeling) Islands Emoji
🇨🇩 Flag: Congo - Kinshasa Emoji
🇨🇫 Flag: Central African Republic Emoji
🇨🇬 Flag: Congo - Brazzaville Emoji
🇨🇭 Flag: Switzerland Emoji
🇨🇮 Flag: Côte D Ivoire Emoji
🇨🇰 Flag: Cook Islands Emoji
🇨🇱 Flag: Chile Emoji
🇨🇲 Flag: Cameroon Emoji
🇨🇳 Flag: China Emoji
🇨🇴 Flag: Colombia Emoji
🇨🇵 Flag: Clipperton Island Emoji
🇨🇷 Flag: Costa Rica Emoji
🇨🇺 Flag: Cuba Emoji
🇨🇻 Flag: Cape Verde Emoji
🇨🇼 Flag: Curaçao Emoji
🇨🇽 Flag: Christmas Island Emoji
🇨🇾 Flag: Cyprus Emoji
🇨🇿 Flag: Czechia Emoji
🇩🇪 Flag: Germany Emoji
🇩🇯 Flag: Djibouti Emoji
🇩🇰 Flag: Denmark Emoji
🇩🇲 Flag: Dominica Emoji
🇩🇴 Flag: Dominican Republic Emoji
🇩🇿 Flag: Algeria Emoji
🇪🇨 Flag: Ecuador Emoji
🇪🇪 Flag: Estonia Emoji
🇪🇬 Flag: Egypt Emoji
🇪🇷 Flag: Eritrea Emoji
🇪🇸 Flag: Spain Emoji
🇪🇹 Flag: Ethiopia Emoji
🇪🇺 Flag: European Union Emoji
🇫🇮 Flag: Finland Emoji
🇫🇯 Flag: Fiji Emoji
🇫🇲 Flag: Micronesia Emoji
🇫🇴 Flag: Faroe Islands Emoji
🇫🇷 Flag: France Emoji
🇬🇦 Flag: Gabon Emoji
🇬🇧 Flag: United Kingdom Emoji
🇬🇩 Flag: Grenada Emoji
🇬🇪 Flag: Georgia Emoji
🇬🇬 Flag: Guernsey Emoji
🇬🇭 Flag: Ghana Emoji
🇬🇮 Flag: Gibraltar Emoji
🇬🇱 Flag: Greenland Emoji
🇬🇲 Flag: Gambia Emoji
🇬🇳 Flag: Guinea Emoji
🇬🇶 Flag: Equatorial Guinea Emoji
🇬🇷 Flag: Greece Emoji
🇬🇹 Flag: Guatemala Emoji
🇬🇺 Flag: Guam Emoji
🇬🇼 Flag: Guinea-Bissau Emoji
🇬🇾 Flag: Guyana Emoji
🇭🇰 Flag: Hong Kong Sar China Emoji
🇭🇲 Flag: Heard & Mcdonald Islands Emoji
🇭🇳 Flag: Honduras Emoji
🇭🇷 Flag: Croatia Emoji
🇭🇹 Flag: Haiti Emoji
🇭🇺 Flag: Hungary Emoji
🇮🇨 Flag: Canary Islands Emoji
🇮🇩 Flag: Indonesia Emoji
🇮🇪 Flag: Ireland Emoji
🇮🇱 Flag: Israel Emoji
🇮🇲 Flag: Isle Of Man Emoji
🇮🇳 Flag: India Emoji
🇮🇴 Flag: British Indian Ocean Territory Emoji
🇮🇶 Flag: Iraq Emoji
🇮🇷 Flag: Iran Emoji
🇮🇸 Flag: Iceland Emoji
🇮🇹 Flag: Italy Emoji
🇯🇪 Flag: Jersey Emoji
🇯🇲 Flag: Jamaica Emoji
🇯🇴 Flag: Jordan Emoji
🇯🇵 Flag: Japan Emoji
🇰🇪 Flag: Kenya Emoji
🇰🇬 Flag: Kyrgyzstan Emoji
🇰🇭 Flag: Cambodia Emoji
🇰🇮 Flag: Kiribati Emoji
🇹🇷 Flag: Turkey Emoji
🇰🇲 Flag: Comoros Emoji
🇰🇳 Flag: St. Kitts & Nevis Emoji
🇰🇵 Flag: North Korea Emoji
🇰🇷 Flag: South Korea Emoji
🇰🇼 Flag: Kuwait Emoji
🇰🇾 Flag: Cayman Islands Emoji
🇰🇿 Flag: Kazakhstan Emoji
🇱🇦 Flag: Laos Emoji
🇱🇧 Flag: Lebanon Emoji
🇱🇨 Flag: St. Lucia Emoji
🇱🇮 Flag: Liechtenstein Emoji
🇱🇰 Flag: Sri Lanka Emoji
🇱🇷 Flag: Liberia Emoji
🇱🇸 Flag: Lesotho Emoji
🇱🇹 Flag: Lithuania Emoji
🇱🇺 Flag: Luxembourg Emoji
🇱🇻 Flag: Latvia Emoji
🇱🇾 Flag: Libya Emoji
🇲🇦 Flag: Morocco Emoji
🇲🇨 Flag: Monaco Emoji
🇲🇩 Flag: Moldova Emoji
🇲🇪 Flag: Montenegro Emoji
🇲🇬 Flag: Madagascar Emoji
🇲🇭 Flag: Marshall Islands Emoji
🇲🇰 Flag: North Macedonia Emoji
🇲🇱 Flag: Mali Emoji
🇲🇲 Flag: Myanmar (Burma) Emoji
🇲🇳 Flag: Mongolia Emoji
🇲🇴 Flag: Macao Sar China Emoji
🇲🇵 Flag: Northern Mariana Islands Emoji
🇲🇶 Flag: Martinique Emoji
🇲🇷 Flag: Mauritania Emoji
🇲🇸 Flag: Montserrat Emoji
🇲🇹 Flag: Malta Emoji
🇲🇺 Flag: Mauritius Emoji
🇲🇻 Flag: Maldives Emoji
🇲🇼 Flag: Malawi Emoji
🇲🇽 Flag: Mexico Emoji
🇲🇾 Flag: Malaysia Emoji
🇲🇿 Flag: Mozambique Emoji
🇳🇦 Flag: Namibia Emoji
🇳🇪 Flag: Niger Emoji
🇳🇫 Flag: Norfolk Island Emoji
🇳🇬 Flag: Nigeria Emoji
🇳🇮 Flag: Nicaragua Emoji
🇳🇱 Flag: Netherlands Emoji
🇳🇴 Flag: Norway Emoji
🇳🇵 Flag: Nepal Emoji
🇳🇷 Flag: Nauru Emoji
🇳🇺 Flag: Niue Emoji
🇳🇿 Flag: New Zealand Emoji
🇴🇲 Flag: Oman Emoji
🇵🇦 Flag: Panama Emoji
🇵🇪 Flag: Peru Emoji
🇵🇫 Flag: French Polynesia Emoji
🇵🇬 Flag: Papua New Guinea Emoji
🇵🇭 Flag: Philippines Emoji
🇵🇰 Flag: Pakistan Emoji
🇵🇱 Flag: Poland Emoji
🇵🇳 Flag: Pitcairn Islands Emoji
🇵🇷 Flag: Puerto Rico Emoji
🇵🇸 Flag: Palestinian Territories Emoji
🇵🇹 Flag: Portugal Emoji
🇵🇼 Flag: Palau Emoji
🇵🇾 Flag: Paraguay Emoji
🇶🇦 Flag: Qatar Emoji
🇷🇪 Flag: Réunion Emoji
🇷🇴 Flag: Romania Emoji
🇷🇸 Flag: Serbia Emoji
🇷🇺 Flag: Russia Emoji
🇷🇼 Flag: Rwanda Emoji
🇸🇦 Flag: Saudi Arabia Emoji
🇸🇧 Flag: Solomon Islands Emoji
🇸🇨 Flag: Seychelles Emoji
🇸🇩 Flag: Sudan Emoji
🇸🇪 Flag: Sweden Emoji
🇸🇬 Flag: Singapore Emoji
🇸🇭 Flag: St. Helena Emoji
🇸🇮 Flag: Slovenia Emoji
🇸🇯 Flag: Svalbard & Jan Mayen Emoji
🇸🇰 Flag: Slovakia Emoji
🇸🇱 Flag: Sierra Leone Emoji
🇸🇲 Flag: San Marino Emoji
🇸🇳 Flag: Senegal Emoji
🇸🇴 Flag: Somalia Emoji
🇸🇷 Flag: Suriname Emoji
🇸🇸 Flag: South Sudan Emoji
🇸🇹 Flag: São Tomé & Príncipe Emoji
🇸🇻 Flag: El Salvador Emoji
🇸🇽 Flag: Sint Maarten Emoji
🇸🇾 Flag: Syria Emoji
🇸🇿 Flag: Eswatini Emoji
🇹🇦 Flag: Tristan Da Cunha Emoji
🇹🇨 Flag: Turks & Caicos Islands Emoji
🇹🇩 Flag: Chad Emoji
🇹🇫 Flag: French Southern Territories Emoji
🇹🇬 Flag: Togo Emoji
🇹🇭 Flag: Thailand Emoji
🇹🇯 Flag: Tajikistan Emoji
🇹🇰 Flag: Tokelau Emoji
🇹🇱 Flag: Timor-Leste Emoji
🇹🇲 Flag: Turkmenistan Emoji
🇹🇳 Flag: Tunisia Emoji
🇹🇴 Flag: Tonga Emoji
🇹🇹 Flag: Trinidad & Tobago Emoji
🇹🇻 Flag: Tuvalu Emoji
🇹🇼 Flag: Taiwan Emoji
🇹🇿 Flag: Tanzania Emoji
🇺🇦 Flag: Ukraine Emoji
🇺🇬 Flag: Uganda Emoji
🇺🇲 Flag: U.S. Outlying Islands Emoji
🇺🇳 Flag: United Nations Emoji
🇺🇾 Flag: Uruguay Emoji
🇺🇿 Flag: Uzbekistan Emoji
🇻🇦 Flag: Vatican City Emoji
🇻🇨 Flag: St. Vincent & Grenadines Emoji
🇻🇪 Flag: Venezuela Emoji
🇻🇬 Flag: British Virgin Islands Emoji
🇻🇮 Flag: U.S. Virgin Islands Emoji
🇻🇳 Flag: Vietnam Emoji
🇻🇺 Flag: Vanuatu Emoji
🇼🇸 Flag: Samoa Emoji
🇽🇰 Flag: Kosovo Emoji
🇾🇪 Flag: Yemen Emoji
🇿🇦 Flag: South Africa Emoji
🇿🇲 Flag: Zambia Emoji
🇿🇼 Flag: Zimbabwe Emoji
🎌 Crossed Flags Emoji
🏳 White Flag Emoji
🏳️‍🌈 Rainbow Flag Emoji
🏴 Black Flag Emoji
🏴‍☠️ Pirate Flag Emoji
🚩 Triangular Flag Emoji
🏴󠁧󠁢󠁥󠁮󠁧󠁿 Flag: England Emoji
🏴󠁧󠁢󠁳󠁣󠁴󠁿 Flag: Scotland Emoji
🏴󠁧󠁢󠁷󠁬󠁳󠁿 Flag: Wales Emoji


🦰 Component


🦰 Red Hair Emoji
🦱 Curly Hair Emoji
🦲 Bald Emoji
🦳 White Hair Emoji
## Recent Updates

    📘 Math
    ☪️️ Muslim
    🏛 World Day of Architecture
    🏳️‍🌈 Gay

## Popular

    😂 Face With Tears of Joy
    ❤️ Red Heart
    😘 Face Blowing a Kiss
    ✨ Sparkles
    🔥 Fire
    🦋 Butterfly
    🥳 Partying Face
    🍭 Lollipop
    💕 Two Hearts
    🌝 Full Moon Face

## Holidays

    🎁 Christmas
    🎄 New Years Eve
    🐲 Chinese New Year
    💖 Valentines Day
    🐿 Groundhog Day
    ☘️ St Patricks Day
    👩 Women’s Day
    👩‍👧‍👦 Mothers Day
    🙆‍♂️ April Fool’s Day
    ☪️️ Ramadan
    🇺🇸 Independence Day
    👨‍💼 Presidents’ Day
    👨‍👧‍👦 Fathers Day
    🎃 Halloween
    🌺 Remembrance Day
    🦃 Thanksgiving Day
    🕎 Hanukkah
    👤🔥 Burning Man
    🏛 World Day of Architecture
    See the full list...

## Themes

    🎂 Birthday
    🥚🐇 Easter
    ✝️️ Christian
    ☪️️ Muslim
    👽 Space
    🏳️‍🌈 Gay
    📘 Math
    🌸 Spring
    🌻 Summer
    🍺 Alcohol
    ⚡🧙 Harry Potter
    🦸‍♂️ Avengers
    🌌🔫 Star Wars
    🧽 SpongeBob SquarePants
    ⛏🧱 Minecraft
    🤫👨‍🚀🔫 Among us
    See the full list...

    Apple
    Google
    Microsoft
    Facebook
    Messenger
    Twitter
    WhatsApp
    Samsung
    LG
    HTC
    Mozilla
    SoftBank
    au by KDDI
    Docomo
    Openmoji
    Youtube
    Telegram
    Skype
    Discord
    TikTok
    Reddit
    Animoji
    Emoji Kitchen
    Bitmoji
    Sony Playstation

    Emoji version 1.0
    Emoji Version 2.0
    Emoji Version 3.0
    Emoji Version 4.0
    Emoji Version 5.0
    Emoji Version 11.0
    Emoji Version 12.0
    Emoji Version 12.1
    Emoji Version 13.0
    Emoji Version 13.1
    Emoji Version 14.0

    Help
    Privacy Policy
    Trademarks
    About

# site logo logo
# Made with ❤️, 🥛 and 🐹 in 2017-2021.
# facebook
# twitter
# pinterest
# tik tok
# youtube
# instagram
# 🌚
# x
# 
