#!/bin/bash
#!/usr/bin/env ash
set -eu

o=${0##*/}

case $1 in --help)
	case $o in
		micro-diff)
			printf %s\\n "Usage: $o [..diff arguments] <file to diff>"
		;;
		micro-diff-?*)
			printf %s\\n \
				"Usage: $o [...args] <file path>" \
				" executes: ${o#"micro-diff-"} [...same args] ~/.config/micro/(<file path>)" \
			;
		;;
		*) exit 2;;
	esac
	exit
esac


unset i
case $# in
	0) echo required an argument; exit 1;;
	1) i=$1; shift;;
	2) i=$2; set -- "$1";; # most of the times -> expected from my `alias micro-diff='\micro-diff --color=auto'`
	*) . ~/B/__sourceable/pop_to_i.sh;;
esac


unset j
case $i in /*) j=$i;; *) j=$PWD/$i; esac

# TODO: detect if its ash , else iterate replace / with %

case $o in
	micro-diff)    exec diff               "$@" "$i" ~/.config/micro/backups/"${j////"%"}";;
	micro-diff-?*) exec "${o#micro-diff-}" "$@"      ~/.config/micro/backups/"${j////"%"}";;
esac
