#!/bin/bash
#!/bin/sh

# if case $1 in --com= # consider: add --com=command option
if [ -t 1 ]; then
	eval "comm () { ${LSLONG_COMMAND:-ls -al} -d -- \"\$@\"; }"
else
	comm () {
		if [ $# -eq 1 ] && [ -e "$1" ]; then
			printf %s\\n "$@"
		else
			printf %s\\n >&2 "no such a file: $1"
			return 1
		fi
	}
fi

i=.
IFS=''
shopt -s dotglob

while
	! comm $i/$* || {
		YN_confirm -S y continue
	}
do
	i=$i/*
	printf %s\\n "pattern: $i/$*" >&2 
done
