#!/bin/bash
#!/bin/sh
# only use bash for conviniance of 'dotglob'

#case ${1-} in
#	-f) shift; exec dash "$0" "$@";; # for fast (TODO: detect if current shell is already dash, if there is env/non-env var from dash)
#	--) shift;
#esac


# if case $1 in --com= # consider: add --com=command option
if [ -t 1 ]; then
	eval "comm () { ${LSLONG_COMMAND:-ls -al} -d -- \"\$@\"; }"
else
	comm () {
		if [ $# -eq 1 ] && [ -e "$1" ]; then
			printf %s\\n "$@"
		else
			printf %s\\n >&2 "no such a file: $1"
			return 1
		fi
	}
fi

i=.
IFS=''
shopt -s dotglob

while
	! comm $i/$* || {
		YN_confirm -S y continue
	}
do
	i=$i/*
	printf %s\\n "pattern: $i/$*" >&2 
done
