#!/bin/sh

# if case $1 in --com= # consider: add --com=command option
if [ -t 1 ]; then
	comm () { ll -d -- "$@"; }
else
	comm () {
		if [ $# -eq 1 ] && [ -e "$1" ]; then
			printf %s\\n "$@"
		else
			case $? in
				1) printf %s\\n >&2 "no such a file: $1"; return 1;;
				*)
					local i;i=$i
					printf %s\\n >&2 "unexpected 'test' exit code: ($i) : $1"
					return $i
				;;
			esac
			return 1
		fi
	}
fi

i=.
IFS=''

while
	! comm $i/$* || {
		YN_confirm y continue
	}
do
	i=$i/*
done
