#!/bin/sh
set -feu

raw=-raw
to_shift=$#
while case $to_shift in 0) false; esac; do

	case ${1#"-"} in
		-no-raw|-noraw) raw='';;
		help|-help) exec tt --help;;
		"${1#?}") set -- "$@" "$1";;
		*) printf %s\\n "${0##*/}: unrecognised argument -- '$1'"; exit 1;;
	esac

	to_shift=$(( to_shift - 1 ));shift

done


IFS='~'
YN_confirm_path=$(which YN_confirm 2>&-) && YN_confirm () { unset -f YN_confirm; . "$YN_confirm_path"; YN_confirm "$@"; } # lazy load the YN_confirm file

for i in $( sed --null-data 's/\n\n/~/g; s/\n/ \n/g' ); do
# for i in $( $ cout | sed --null-data 's/\n\n/~/g; s/\n/ \n/g' ); do
	#                tt -noreport # DOES IT NEED IT ?
	printf %s "$i" | \tt $raw -oneshot "$@" || {
		stat=$?
		YN_confirm Y "Exit now?" </dev/tty >/dev/tty && exit $stat
	}
done
