#!/bin/sh
##arg "$@" >&2
set -feu

raw=-raw
to_shift=$#
while case $to_shift in 0) false; esac; do

	case ${1#"-"} in
		-no-raw|-noraw) raw='';;
		help|-help) echo "usage? huuh, just put -no-raw"; exit 1;;
		"${1#?}") set -- "$@" "$1";;
		*) printf %s\\n "${0##*/}: unrecognised argument -- '$1'"; exit 1;;
	esac

	to_shift=$(( to_shift - 1 ));shift

done


IFS='~'
i=$(which YN_confirm 2>&-) && . "$i"

for i in $( sed --null-data 's/\n\n/~/g; s/\n/ \n/g' ); do
# for i in $( $ cout | sed --null-data 's/\n\n/~/g; s/\n/ \n/g' ); do
	#                tt -noreport # DOES IT NEED IT ?
	printf %s "$i" | \tt $raw -oneshot "$@" || {
		stat=$?
		YN_confirm Y "Exit now?" </dev/tty >/dev/tty && exit $stat
	}
done
