#!/bin/bash
set -eu

o=${0##*/}

case ${1-} in --help)
	case $o in
		micro-diff)
			printf %s\\n "Usage: $o [..diff arguments] <file to diff>"
		;;
		micro-diff-?*)
			printf %s\\n \
				"Usage: $o [...args] <file path>" \
				" executes: ${o#"micro-diff-"} [...same args] ~/.config/micro/(<file path>)" \
			;
		;;
		*) exit 2;;
	esac
	exit
esac

case $# in 0) echo "use --help for usage" >&2; exit 2; esac

# pop last arg to var `i`
# this is from https://github.com/denisde4ev/shrc/blob/master/__sourceable/pop_to_i.bash
# (for POSIX sh pop_to_i.sh)
i=$#
i=${!i}
set -- "${@:1:$#-1}"

unset j
case $i in /*) j=$i;; *) j=$PWD/$i; esac

case $o in
	micro-diff)    exec diff               "$@" "$i" ~/.config/micro/backups/"${j////"%"}";;
	micro-diff-?*) exec "${o#micro-diff-}" "$@"      ~/.config/micro/backups/"${j////"%"}";;
esac
