#!/bin/bash
set -eu

# when edit this file conider editing and ../micro-diff

micro_conf_bac=~/.config/micro/backups


o=${0##*/}

case ${1-} in --help)
	printf %s\\n "Usage: $o [..diff arguments] [file to diff]"
	exit
esac


# pop last arg to var `i`
# this is from https://github.com/denisde4ev/shrc/blob/master/__sourceable/pop_to_i.bash
# (for POSIX sh pop_to_i.sh)
i=$#
i=${!i}
set -- "${@:1:$#-1}"

case ${i+i}:${i-} in :|i:-*)  # if only option is specifyed, it will be ignored
	case $LSLONG_COMMAND-} in
		*[!"$IFS"]*) exec ${LSLONG_COMMAND} "$micro_conf_bac";;
		*)           exec ls -al            "$micro_conf_bac";;
	esac
esac

unset j
case $i in /*) j=$i;; *) j=$PWD/$i; esac

case $o in
	micro-diff)    exec diff               "$@" "$i" "$micro_conf_bac"/"${j////"%"}";;
	micro-diff-?*) exec "${o#micro-diff-}" "$@"      "$micro_conf_bac"/"${j////"%"}";;
esac
