#!/bin/bash
set -eu

# when edit this file conider editing ../micro-diff as well

micro_conf_bac=~/.config/micro/backups


case ${1-} in --help)
	printf %s\\n \
		"Usage: ${0##*/} [..diff arguments] [file to diff]" \
	;
	exit
esac

err() { printf %s\\n >&2 "${0##*/}: $1"; exit $2; }

case $# in 0) ;; *)
	# pop last arg to var `i`
	# this is from https://github.com/denisde4ev/shrc/blob/master/__sourceable/pop_to_i.bash
	# (for POSIX sh pop_to_i.sh)
	i=$#
	i=${!i}
	set -- "${@:1:$#-1}"
esac


shopt -s nullglob

case ${i+i}:${i-} in
:|i:-*)  # if no arguments or if last arg is armument (woraround for this check is ./-file)
	if [ -t 1 ]; then
		ls -al "$micro_conf_bac"/*
	else
		printf %s\\n "$micro_conf_bac"/*
	fi
	exit
	;;
esac

[ ! -d "$i" ] || err "diffing dir is not implemented" 3

unset j
case $i in /*) j=$i;; *) j=$PWD/$i;; esac
j=$micro_conf_bac"/"${j////"%"}

[ -t 1 ] || {
	printf %s\\n "$j"
	exit
}

exec diff "$@" "$i" "$j"
