#!/bin/bash

# exec sudo --login "$@"
# exit 1

# Waring: /bin/sudo might not be the path in avery distro


case "$1" in
	o) set -- "${@:2}";;
	o*) set -- "${1#o}" "${@:2}";;
	'') [ "$#" = 0 ] && exec /bin/sudo --login;;
esac
echo /bin/sudo "$@" >&2
exec /bin/sudo "$@"
