#!/bin/bash

case $1 in
	o)  set -- "${@:2}";; # sud o dd
	o*) set -- "${1#o}" "${@:2}";;  # sud odd
	'') [ $# = 0 ] && exec sudo --login;; # hope sudo is not symlink to doas or another wrapper/proxy
esac

echo sudo "$@" >&2
exec sudo "$@"
