#!/bin/sh

case $1 in
	--help|-h) echo "Usage: ${0##*/} <number-to-cal>"; exit;;
	*[!0-9\+\ \-]*) echo 'use -h for usage' >&2; exit 2;;
esac

termux--unlock-screen
am start -a android.intent.action.CALL -d tel:"$@"
