#!/usr/bin/env node

function exit($1) {
	if (typeof $1 === 'boolean') {
		$1 = +!$1;
	} /* else if (typeof $1 === 'undefined') {
		$1 = 0;
	} */
	process.exit($1);
	return $1;
}

function echo($1) {
	return process.stdout.write($1+'\n');
}

var [$0_node, $0, $args] = process.argv;
var [$1, $2, $3] = $args;
var $o = $0.match(/[^\/]*$/)[0]; // fix*/

if ($1 === '--help') {
	echo(`Usage: ${$o} x|c [-f FILE]`);
	exit(0);
} else if (/^[^-]/.test($1)) {
	$args[0] = $1 = '-'+$1;
}


function shift($1) {
	if ($args.length < $1) {
		return false;
	} 
	args.splice(0,$1);
	[$1, $2, $3] = $args;
	return true;
}

while (0 < args.length) {
	if ($1) // TODO: HERE
	if ($1 === '-') {
		;
	} else if () {
		;
	}
}
